baseURL: https://kitsonkelly.com/
languageCode: en-gb
title: "Kitson P. Kelly Blog"
theme: "toha"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable Google Analytics
googleAnalytics: UA-42376316-1

# Enable Disqus forum
disqusShortname: kitsonkelly

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  # Copyright Notice
  copyright: Â© 2017-2020 Kitson P. Kelly.

  # Meta description for your site.  This will help the search engines to find your site.
  description: Homepage and blog for Kitson Kelly

  # background image of the landing page
  background: "images/bg_green.jpg"

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will be default to the theme logos if not provided.
  logo:
    main: /images/cactus_logo_black.png
    inverted: /images/cactus_logo_white.png

  # GitHub repo URL of your site
  gitRepo: https://github.com/kitsonk/kitsonkelly.com

  # specify whether you want to write blog post or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false

  # some information about you
  author:
    name: "Kitson Kelly"
    nickname: "Kit"
    image: "images/kpk_512.jpeg"
    # greeting message before your name. it will default to "Hi! I am" if not provided
    greeting: "Hello, I am"
    # give your some contact information. they will be used in the footer
    contactInfo:
      email: "me@kitsonkelly.com"
    # a summary of what you do
    summary:
    - I am a father
    - I am a technologist
    - I work on Deno
    - I have lots of opinions
